version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/main}:/var/lib/localstack"
      # - "$HOME/.colima/default/docker.sock:/var/run/docker.sock"
      # - "/var/run/docker.sock:/var/run/docker.sock"
  sqs:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_sqs}"
    image: localstack/localstack
    ports:
      - "4567:4566"
      - "4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./bootstrap/sqs:/etc/localstack/init/ready.d
      - ./volumes/sqs:/var/lib/localstack"
